export interface DemoProject {
  id: string
  name: string
  description: string
  default_latitude: number
  default_longitude: number
  default_zoom: number
  status: string
  organization_id: string
  created_at: string
  updated_at: string
}

export const DEMO_PROJECT: DemoProject = {
  id: 'demo-metro-cctv',
  name: 'Atlanta Beltline Fiber & CCTV Infrastructure Grid',
  description: 'High-density urban CCTV surveillance deployment featuring 24-strand single-mode fiber backbone, industrial PoE switches, and GIS node tracking.',
  default_latitude: 33.7490,
  default_longitude: -84.3880,
  default_zoom: 16,
  status: 'Active',
  organization_id: 'org-demo-001',
  created_at: '2026-07-15T10:00:00Z',
  updated_at: '2026-08-23T12:00:00Z',
}

export const DEMO_CAMERAS = [
  {
    id: 'cam-001',
    project_id: 'demo-metro-cctv',
    camera_id_tag: 'CAM-001',
    name: 'BeltLine West Trail Junction - PTZ',
    latitude: 33.7495,
    longitude: -84.3892,
    mounting_type: 'Pole',
    resolution: '4K UHD (3840x2160)',
    fps: 30,
    field_of_view_degrees: 360,
    install_status: 'Installed',
    notes: 'Connected to Fiber Cabinet CAB-001 via Drop Cable. [IP: 192.168.10.101] [VLAN: 10] [Switch: SW-DIST-01, Port: 1] [Connectivity: Direct Fiber Drop]',
    camera_model_id: 'model-axis-q6135',
  },
  {
    id: 'cam-002',
    project_id: 'demo-metro-cctv',
    camera_id_tag: 'CAM-002',
    name: 'South Avenue Pedestrian Bridge Bullet',
    latitude: 33.7482,
    longitude: -84.3875,
    mounting_type: 'Structure',
    resolution: '5MP (2560x1920)',
    fps: 30,
    field_of_view_degrees: 90,
    install_status: 'Installed',
    notes: 'Monitors pedestrian underpass. [IP: 192.168.10.102] [VLAN: 10] [Switch: SW-DIST-01, Port: 2] [Connectivity: Direct Fiber Drop]',
    camera_model_id: 'model-hanwha-xnv',
  },
  {
    id: 'cam-003',
    project_id: 'demo-metro-cctv',
    camera_id_tag: 'CAM-003',
    name: 'North Entrance License Plate Reader',
    latitude: 33.7505,
    longitude: -84.3860,
    mounting_type: 'Pole',
    resolution: '4K LPR Dedicated',
    fps: 60,
    field_of_view_degrees: 45,
    install_status: 'Planned',
    notes: 'Vehicle LPR at access gate. [IP: 192.168.10.103] [VLAN: 20] [Switch: SW-DIST-02, Port: 1] [Connectivity: Direct Fiber Drop]',
    camera_model_id: 'model-axis-p3245',
  },
  {
    id: 'cam-004',
    project_id: 'demo-metro-cctv',
    camera_id_tag: 'CAM-004',
    name: 'East Plaza Multi-Sensor 360',
    latitude: 33.7512,
    longitude: -84.3888,
    mounting_type: 'Pole',
    resolution: '20MP Multi-Directional',
    fps: 30,
    field_of_view_degrees: 360,
    install_status: 'Installed',
    notes: 'Covers main civic plaza. [IP: 192.168.10.104] [VLAN: 10] [Switch: SW-DIST-01, Port: 3] [Connectivity: Direct Fiber Drop]',
    camera_model_id: 'model-axis-q6135',
  },
]

export const DEMO_FIBER_DATA = {
  nodes: [
    {
      id: 'node-001',
      project_id: 'demo-metro-cctv',
      node_id_tag: 'CAB-001',
      node_type: 'Cabinet',
      status: 'Installed',
      latitude: 33.7490,
      longitude: -84.3880,
      location_description: 'Main Telecom Distribution Cabinet - West Plaza',
    },
    {
      id: 'node-002',
      project_id: 'demo-metro-cctv',
      node_id_tag: 'MH-001',
      node_type: 'Manhole',
      status: 'Installed',
      latitude: 33.7498,
      longitude: -84.3890,
      location_description: 'Heavy Duty Concrete Vault at BeltLine Intersection',
    },
    {
      id: 'node-003',
      project_id: 'demo-metro-cctv',
      node_id_tag: 'HH-002',
      node_type: 'Handhole',
      status: 'Installed',
      latitude: 33.7480,
      longitude: -84.3870,
      location_description: 'Composite Handhole Box near South Pedestrian Bridge',
    },
    {
      id: 'node-004',
      project_id: 'demo-metro-cctv',
      node_id_tag: 'PB-003',
      node_type: 'Pull Box',
      status: 'Planned',
      latitude: 33.7510,
      longitude: -84.3865,
      location_description: 'Conduit Pull Box near East Plaza Entrance',
    },
  ],
  routes: [
    {
      id: 'route-001',
      project_id: 'demo-metro-cctv',
      route_id_tag: 'RTE-MAIN-01',
      status: 'Installed',
      installation_type: 'Underground Conduit',
      route_purpose: 'Backbone',
      conduit_diameter_inches: 4,
      measured_length_feet: 450,
      installed_length_feet: 480,
      from_node_id: 'node-001',
      to_node_id: 'node-002',
    },
    {
      id: 'route-002',
      project_id: 'demo-metro-cctv',
      route_id_tag: 'RTE-SOUTH-02',
      status: 'Installed',
      installation_type: 'Underground Conduit',
      route_purpose: 'Distribution',
      conduit_diameter_inches: 2,
      measured_length_feet: 380,
      installed_length_feet: 400,
      from_node_id: 'node-001',
      to_node_id: 'node-003',
    },
    {
      id: 'route-003',
      project_id: 'demo-metro-cctv',
      route_id_tag: 'RTE-EAST-03',
      status: 'Planned',
      installation_type: 'Underground Conduit',
      route_purpose: 'Distribution',
      conduit_diameter_inches: 2,
      measured_length_feet: 520,
      installed_length_feet: 550,
      from_node_id: 'node-002',
      to_node_id: 'node-004',
    },
  ],
  segments: [
    { id: 'seg-1', route_id: 'route-001', sequence_order: 1, start_latitude: 33.7490, start_longitude: -84.3880, end_latitude: 33.7498, end_longitude: -84.3890, segment_length_feet: 450 },
    { id: 'seg-2', route_id: 'route-002', sequence_order: 1, start_latitude: 33.7490, start_longitude: -84.3880, end_latitude: 33.7480, end_longitude: -84.3870, segment_length_feet: 380 },
    { id: 'seg-3', route_id: 'route-003', sequence_order: 1, start_latitude: 33.7498, start_longitude: -84.3890, end_latitude: 33.7510, end_longitude: -84.3865, segment_length_feet: 520 },
  ],
  cables: [
    {
      id: 'cable-001',
      project_id: 'demo-metro-cctv',
      cable_id_tag: 'FIB-BB-24F',
      route_id: 'route-001',
      fiber_count: 24,
      fiber_type: 'Single-Mode OS2',
      install_status: 'Installed',
      test_status: 'Passed',
      measured_length_feet: 480,
    },
    {
      id: 'cable-002',
      project_id: 'demo-metro-cctv',
      cable_id_tag: 'FIB-DIST-12F',
      route_id: 'route-002',
      fiber_count: 12,
      fiber_type: 'Single-Mode OS2',
      install_status: 'Installed',
      test_status: 'Passed',
      measured_length_feet: 400,
    },
  ],
  enclosures: [
    {
      id: 'enc-001',
      node_id: 'node-002',
      enclosure_type: 'Dome Closure',
      status: 'Installed',
      max_splice_capacity: 48,
    },
  ],
}

export const DEMO_DEVICES = [
  {
    id: 'dev-001',
    project_id: 'demo-metro-cctv',
    device_name: 'SW-DIST-01',
    device_type: 'Industrial Switch',
    ip_address: '192.168.10.2',
    mac_address: '00:1B:C0:A1:3F:01',
    location_description: 'Telecom Cabinet CAB-001 (Rack Unit 4)',
    install_status: 'Active',
    total_ports: 24,
    poe_budget_watts: 370,
  },
  {
    id: 'dev-002',
    project_id: 'demo-metro-cctv',
    device_name: 'SW-DIST-02',
    device_type: 'Industrial Switch',
    ip_address: '192.168.10.3',
    mac_address: '00:1B:C0:A1:3F:02',
    location_description: 'Plaza Vault MH-001 Enclosure',
    install_status: 'Active',
    total_ports: 12,
    poe_budget_watts: 240,
  },
]

export const DEMO_BOM_ITEMS = [
  {
    id: 'bom-001',
    project_id: 'demo-metro-cctv',
    item_category: 'Cameras',
    part_number: 'AXIS-Q6135-LE',
    description: 'Axis Q6135-LE 4K Outdoor PTZ Camera with Radar-PTZ Fusion',
    quantity: 4,
    unit_cost: 2450.00,
    total_cost: 9800.00,
    supplier: 'Anixter / WESCO',
  },
  {
    id: 'bom-002',
    project_id: 'demo-metro-cctv',
    item_category: 'Network Equipment',
    part_number: 'IE-3400-8P2S-A',
    description: 'Cisco Industrial Ethernet 3400 Switch (8 PoE+ Ports, 2 SFP Uplinks)',
    quantity: 2,
    unit_cost: 1850.00,
    total_cost: 3700.00,
    supplier: 'Cisco Direct',
  },
  {
    id: 'bom-003',
    project_id: 'demo-metro-cctv',
    item_category: 'Fiber & Cabling',
    part_number: 'CORNING-24F-OS2',
    description: 'Corning ALTOS 24-Strand Single-Mode Armored Outdoor Cable (Footage)',
    quantity: 1500,
    unit_cost: 1.85,
    total_cost: 2775.00,
    supplier: 'Corning Cable Systems',
  },
  {
    id: 'bom-004',
    project_id: 'demo-metro-cctv',
    item_category: 'Cabinets & Enclosures',
    part_number: 'NEMA-4X-CAB-01',
    description: 'NEMA 4X Stainless Steel Outdoor Telecom Cabinet with Heat Exchanger',
    quantity: 2,
    unit_cost: 3200.00,
    total_cost: 6400.00,
    supplier: 'Hoffman Enclosures',
  },
]

export const DEMO_TASKS = [
  {
    id: 'task-001',
    project_id: 'demo-metro-cctv',
    task_name: 'Mount & Calibrate CAM-001 PTZ Camera at Pole 14',
    status: 'completed',
    priority: 'high',
    assigned_to: 'Tech Lead - Alex R.',
    due_date: '2026-08-20',
  },
  {
    id: 'task-002',
    project_id: 'demo-metro-cctv',
    task_name: 'Perform Fusion Splicing of 24F SMF Cable at Vault MH-001',
    status: 'in_progress',
    priority: 'high',
    assigned_to: 'Fiber Crew A - Carlos M.',
    due_date: '2026-08-25',
  },
  {
    id: 'task-003',
    project_id: 'demo-metro-cctv',
    task_name: 'OTDR Trace Retest for Route RTE-SOUTH-02',
    status: 'todo',
    priority: 'medium',
    assigned_to: 'QA Tech - Elena G.',
    due_date: '2026-08-28',
  },
]
