'use client'

import React, { useState } from 'react'

export default function GlobalReportsPage() {
  const [selectedReport, setSelectedReport] = useState<any>(null)
  const [previewReport, setPreviewReport] = useState<any>(null)
  const [toastMessage, setToastMessage] = useState<string | null>(null)

  const showToast = (msg: string) => {
    setToastMessage(msg)
    setTimeout(() => setToastMessage(null), 3000)
  }

  const globalReports = [
    {
      title: 'Projects Summary',
      desc: 'High-level dashboard summary of all deployed, active, and pending projects across the organization.',
      sections: 'Timeline charts, status breakdown, project cost stats, site maps',
      status: 'Ready'
    },
    {
      title: 'Active Projects Report',
      desc: 'Operational summary of active designs showing milestones, workflow progress, and team workload.',
      sections: 'Milestone tracking, active checklists, team member logs, next tasks',
      status: 'Ready'
    },
    {
      title: 'Equipment Usage Report',
      desc: 'Aggregated analytics of hardware and parts selected across all projects (useful for bulk procurement).',
      sections: 'Total cameras by model, total switches, total fiber conduit distance',
      status: 'Draft / Coming Soon'
    },
    {
      title: 'Open Tasks Across Projects',
      desc: 'Task matrix aggregating all field tech checklists, fiber testing, and camera installation tickets.',
      sections: 'High priority tasks, assigned technicians, project delays, open tickets',
      status: 'Draft / Coming Soon'
    },
    {
      title: 'BOM Summary Across Projects',
      desc: 'Consolidated Bill of Materials for all projects. Exports parts and counts for purchase orders.',
      sections: 'Consolidated materials sheet, estimated costs, vendor part list',
      status: 'Draft / Coming Soon'
    },
    {
      title: 'Recent Exports',
      desc: 'Audit trail of PDF blueprints, CAD exports, and KMZ files generated by designers.',
      sections: 'Timestamped links, output formats, export file sizes, editor history',
      status: 'Ready'
    },
    {
      title: 'Client Deliverables Index',
      desc: 'Aggregated documentation packages, user guides, closeout records, and test reports.',
      sections: 'PDF packages, closeout signatures, fiber test OTDR curves',
      status: 'Draft / Coming Soon'
    }
  ]

  const handleGenerateReport = (report: any) => {
    setPreviewReport(report)
  }

  return (
    <div className="space-y-8 w-full px-6 py-8 font-sans text-slate-100 bg-[#0c0f1d] min-h-full overflow-y-auto scrollbar-thin relative">
      
      {/* Toast alert */}
      {toastMessage && (
        <div className="fixed top-4 right-4 z-50 bg-slate-900 border border-slate-750 text-white px-4 py-3 rounded-xl shadow-2xl animate-in slide-in-from-top-4 duration-200 text-xs font-bold font-mono flex items-center gap-2">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
          {toastMessage}
        </div>
      )}

      {/* Title Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2.5xl font-black text-white tracking-tight leading-none">
            Global Reports
          </h1>
          <p className="text-sm text-slate-400 mt-2 font-medium">
            Cross-project reports, bulk statistics, and procurement deliverables.
          </p>
        </div>
        <span className="text-[10px] font-black uppercase px-2.5 py-1 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 tracking-wider">
          Company level
        </span>
      </div>

      {/* Grid List */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {globalReports.map((r, i) => (
          <div
            key={i}
            className="bg-slate-900/40 border border-slate-850 p-6 rounded-2xl flex flex-col justify-between space-y-4 hover:border-slate-800 transition"
          >
            {/* Header info */}
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <h3 className="font-extrabold text-white text-base">{r.title}</h3>
                <span className={`text-[8.5px] font-black px-2 py-0.5 rounded-md uppercase tracking-wider font-mono ${
                  r.status === 'Ready' 
                    ? 'bg-emerald-500/10 text-emerald-450 border border-emerald-500/20' 
                    : 'bg-slate-950 text-slate-500'
                }`}>{r.status}</span>
              </div>
              <p className="text-xs text-slate-400 leading-relaxed">{r.desc}</p>
            </div>

            {/* Details container */}
            <div className="bg-slate-950/30 p-4 rounded-xl border border-slate-900 text-[10.5px] font-mono text-slate-450">
              <strong className="text-slate-350">Included Metrics:</strong>
              <p className="text-slate-400 mt-0.5 leading-snug">{r.sections}</p>
            </div>

            {/* Action button */}
            {r.status === 'Ready' ? (
              <button
                type="button"
                onClick={() => handleGenerateReport(r)}
                className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition tracking-wide cursor-pointer active:scale-98"
              >
                Generate Report
              </button>
            ) : (
              <button
                type="button"
                onClick={() => setSelectedReport(r)}
                className="w-full py-2.5 bg-slate-950 border border-slate-850 hover:border-slate-750 text-slate-400 rounded-xl text-xs font-bold transition tracking-wide cursor-pointer active:scale-98"
              >
                View Scope — Coming Soon
              </button>
            )}
          </div>
        ))}
      </div>

      {/* Report Scope / Coming Soon Modal */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-950/70 backdrop-blur-xs" onClick={() => setSelectedReport(null)} />
          <div className="relative bg-slate-900 border border-slate-800 p-6 rounded-2xl w-full max-w-md space-y-4 shadow-2xl animate-in zoom-in-95 duration-150">
            <div>
              <span className="text-[9px] font-bold uppercase text-slate-500 tracking-widest font-mono">Report Scope</span>
              <h3 className="text-sm font-black uppercase text-indigo-400 tracking-wider mt-0.5">{selectedReport.title}</h3>
              <p className="text-[11px] text-slate-450 leading-relaxed mt-2">{selectedReport.desc}</p>
            </div>

            <div className="space-y-3.5 text-xs font-mono bg-slate-950/40 p-4 border border-slate-900 rounded-xl text-slate-400">
              <div className="space-y-1">
                <span className="text-[9px] font-bold text-slate-550 uppercase">Planned Data Integrations</span>
                <p className="text-slate-350 leading-relaxed">{selectedReport.sections}</p>
              </div>

              <div className="pt-2 border-t border-slate-900 text-rose-500 font-bold flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-pulse" />
                Status: Coming Soon
              </div>
            </div>

            <div className="flex justify-end pt-2">
              <button type="button" onClick={() => setSelectedReport(null)} className="px-4 py-2 bg-slate-950 border border-slate-800 hover:border-slate-750 text-slate-350 rounded-xl text-xs font-bold transition">
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Report Preview Modal */}
      {previewReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-950/70 backdrop-blur-xs" onClick={() => setPreviewReport(null)} />
          <div className="relative bg-slate-900 border border-slate-800 p-6 rounded-2xl w-full max-w-2xl space-y-4 shadow-2xl animate-in zoom-in-95 duration-150">
            <div>
              <span className="text-[9px] font-bold uppercase text-slate-500 tracking-widest font-mono">Mock Report Preview</span>
              <h3 className="text-base font-black uppercase text-indigo-400 tracking-wider mt-0.5">{previewReport.title}</h3>
            </div>

            {/* Mock Data Display */}
            <div className="space-y-4 text-xs font-mono bg-slate-950/40 p-5 border border-slate-900 rounded-xl text-slate-400 max-h-[350px] overflow-y-auto scrollbar-thin">
              <div className="flex justify-between items-center pb-2 border-b border-slate-900">
                <span className="text-[9px] font-bold text-slate-550 uppercase">Report Header</span>
                <span className="text-[9px] text-slate-500">Date: {new Date().toLocaleDateString()}</span>
              </div>

              <div className="space-y-3">
                <div className="p-3.5 bg-slate-900/60 border border-slate-850 rounded-xl space-y-2">
                  <h4 className="font-extrabold text-white text-[11px] uppercase tracking-wide">Executive Summary</h4>
                  <p className="text-[11px] text-slate-400 leading-relaxed font-sans">{previewReport.desc}</p>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="p-3.5 bg-slate-900/60 border border-slate-850 rounded-xl space-y-1.5">
                    <span className="text-[9px] font-bold text-slate-550 uppercase">Target Metrics</span>
                    <p className="text-slate-350 leading-relaxed text-[10.5px]">{previewReport.sections}</p>
                  </div>
                  <div className="p-3.5 bg-slate-900/60 border border-slate-850 rounded-xl space-y-1.5">
                    <span className="text-[9px] font-bold text-slate-550 uppercase">Audit Status</span>
                    <div className="flex items-center gap-1.5 text-emerald-450 font-bold text-[11px] pt-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                      COMPLETED / SEED DATA
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button 
                type="button" 
                onClick={() => showToast('Mock PDF generation complete — starting download.')}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition shadow-md"
              >
                Export PDF (Mock)
              </button>
              <button type="button" onClick={() => setPreviewReport(null)} className="px-4 py-2 bg-slate-950 border border-slate-800 hover:border-slate-750 text-slate-350 rounded-xl text-xs font-bold transition">
                Close Preview
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  )
}
